### ISSUE TITLE
What did you do there

### ISSUE THREAD

**Issue by Felitendo** [Guru322/GURU-Ai#416]
Why did you delete the tiktok dl plugin and why did you comment out the sticker plugin?

https://github.com/Guru322/GURU-Ai/commit/9ca4c08ed9fbeed1a0137366443e392dc2c8efc8

**Comment by Guru322** [comment]
it's temporary , i don't wanna use some libraries , that's why

**Comment by Guru322** [comment]
i will make new versions of those plugins soon

**Comment by Felitendo** [comment]
okay, please do :)
